#! /bin/bash
#InjectionSetup

if [[ ! -d "/Applications/Xcode.app" ]]; then
    exit 0
fi

export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

app="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME"
bundle_src="/Applications/InjectionIII.app/Contents/Resources/iOSDeviceInjection.bundle"
bundle_dst="$app/iOSDeviceInjection.bundle"

function check_arch {
    if [[ "$CONFIGURATION" != "Debug" || "$ARCHS" != "arm64" ]]; then
        exit 0
    fi
}

function check_src() {
    if [[ ! -d "$bundle_src" ]]; then
        echo "Not found iOSDeviceInjection.bundle, expect location:\n$bundle_src"
        exit 0
    fi
}

function sign_bundle() {
    echo "开始签名: $bundle_src"
    find "$bundle_src" -name 'iOSDeviceInjection' | while read file; do sign_bundle_exe "$file"; done
    find "$bundle_src" -name '*.framework' | while read file; do sign "$file"; done
    echo "结束签名"
}

function sign_bundle_exe() {
    echo "iOSDeviceInjection位置： --------- $1"
    /usr/bin/codesign -fs "$EXPANDED_CODE_SIGN_IDENTITY" "$1"
}

function sign() {
    frameworkPath="$1/Versions/A/SwiftTrace"
    echo "执行签名指令： $1"
    echo "$EXPANDED_CODE_SIGN_IDENTITY"
    echo "frameworkPath 目录：$frameworkPath"
    # 获取目标App Bundle identifier($PRODUCT_BUNDLE_IDENTIFIER)，修改 Bundle identifier 为目标App的
    frameworkPlistPath="$1/Info.plist"
    /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $PRODUCT_BUNDLE_IDENTIFIER" $frameworkPlistPath
    /usr/libexec/PlistBuddy -c "Save" $frameworkPlistPath
    echo "修改后的info.plist"
    /usr/libexec/PlistBuddy -c "Print" $frameworkPlistPath
    /usr/bin/codesign -fs "$EXPANDED_CODE_SIGN_IDENTITY" "$frameworkPath"
}

function copy_bundle() {
    if [[ -d "$bundle_dst" ]]; then
        rm -rf "$bundle_dst"
    fi
    cp -af "$bundle_src" "$bundle_dst"
}

function recordSign() {
    echo "$EXPANDED_CODE_SIGN_IDENTITY" > "$bundle_dst/sign"
}

function recordIP() {
    for NUM in $(seq 0 1000); do
        ip=`ipconfig getifaddr en$NUM`
        if [ -n "$ip" ]; then
            break
        fi
    done
    echo "$ip" > "$bundle_dst/ip"
}

check_arch && check_src && sign_bundle && copy_bundle && recordSign && recordIP
